# Generated by Django 3.1 on 2020-10-30 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('employees', '0025_auto_20190529_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.OneToOneField(default='lagos', on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
        ),
    ]
