# Generated by Django 3.1 on 2020-10-30 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('employees', '0026_auto_20201030_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(default='lagos', on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
        ),
    ]
