# Generated by Django 3.1 on 2021-01-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0028_auto_20201031_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='CUG',
            field=models.DecimalField(decimal_places=10, max_digits=45, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='TNO',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='empl_pension',
            field=models.DecimalField(decimal_places=10, max_digits=45, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emplc',
            field=models.DecimalField(decimal_places=10, max_digits=45, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='loan',
            field=models.DecimalField(decimal_places=10, max_digits=45, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='login_id',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='employee',
            name='paye',
            field=models.DecimalField(decimal_places=10, max_digits=45, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_ded',
            field=models.DecimalField(decimal_places=10, max_digits=45, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_Id',
            field=models.CharField(default=1, max_length=45),
        ),
    ]
