# Generated by Django 3.1 on 2021-01-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0029_auto_20210123_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_Id',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
